### DISCUSSION TITLE
Is Tokio actually required?

### DISCUSSION THREAD

**Discussion by John-Nagle** [tursodatabase/turso#734] [Q&A] [answered]
I see a reference to Tokio in Cargo.toml, but not other references. Does Limbo actually need Tokio? I'd like to be able to run without it.

**Comment by penberg** [comment, marked as answer]
Limbo does not require Tokio.

**Reply by John-Nagle** [reply]
Ref: https://github.com/tursodatabase/limbo/blob/4a41736f89f2dd03d5b81e113b21fb5052f1258a/bindings/rust/Cargo.toml#L16

**Comment by bwoods** [comment]
It’s dev dependency, not a normal dependency.

```toml
[dev-dependencies]
tokio = { version = "1.29.1", features = ["full"] }
```

vs.

```toml
[dependencies]
limbo_core = { path = "../../core" }
```

`[dev-dependencies]`s are used for unit/performance testing (for example) and are not build into `lib` or `bin` targets.
