### ISSUE TITLE
Shell input handling is incompatible with `sqlite3`

### ISSUE THREAD

**Issue by penberg** [tursodatabase/turso#966]
If I run multiple statements with `sqlite3`, I get output of all commands:

```
limbo % echo ".show\nSELECT 1" | sqlite3
        echo: off
         eqp: off
     explain: auto
     headers: off
        mode: list
   nullvalue: ""
      output: stdout
colseparator: "|"
rowseparator: "\n"
       stats: off
       width:
    filename: :memory:
1
```

However, `limbo`, returns output from just the first command:

```
limbo % echo ".show\nSELECT 1" | cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.49s
     Running `target/debug/limbo`
Settings:
Output mode: pretty
DB: :memory:
Output: STDOUT
Null value:
CWD: /Users/penberg/src/penberg/limbo
Echo: off
```
